replicaCount: 2
image:
  repository: productapiregistry163505.azurecr.io/productapi
  tag: 65f59ba1cc3d8b60c7c5b98b18b762628c99b4c1
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Production
ingress:
  enabled: true
  host: ""
